[package]
name = "zkfs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
zookeeper-client = "0.8"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
